n=input('Digite algo, verificarei sobre: ')
print('O tipo primitivo desse valor é ',type(n))
print('Esse valor é Alfanumérico ? ',n.isalnum())
print('Esse valor é um número?', n.isnumeric())
print('Esse valor é Letra?',(n.isalpha()))
print('Esse valor é Decimal? ',(n.isdecimal()))
print('Esse valor é Imprimível ?',(n.isprintable()))
print('Está Minúsculo ? ',(n.islower()))
print('Está Maiusculo ?',(n.isupper()))
print('Esse valor é um espaço ?', n.isspace())
print('Está capitalizada?',(n.istitle()))